apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: vote-circuit-breaker
spec:
  host: vote
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
      tcp:
        maxConnections: 1
    outlierDetection:
      baseEjectionTime: 180.000s
      consecutiveErrors: 1
      interval: 1.000s
      maxEjectionPercent: 100